### PR TITLE
Fix: Truncate PR body if exceeds max size

### LINKED ISSUE #194: No error on PR creation failure
When the PR creation fails the action still reports successful execution.

### LINKED ISSUE #197: Pull request creation error - body is too long
If the release notes are too long(more than 65536 characters) then PR creation fails.

### PR DESCRIPTION
**Pull request by sameer-coder**
This PR fixes 2 issues:
- Truncates PR body if it exceeds the 65536 characters limitation set by GitHub
- Sets the action execution to failed if PR creation process fails

Closes #194 
Closes #197

### CODE REVIEW

File: src/utils/releaseNotes.js [hunk 1]
```diff
@@ -30,4 +36,44 @@ function getPrNumbersFromReleaseNotes(releaseNotes) {
...
+  })
+
+  if (prBody.length > MAX_PR_BODY_SIZE_LIMITATION) {
+    const omissionText =
+      '. *Note: Part of the release notes have been omitted from this message, as the content exceeds the size limit*'
+    return _truncate(prBody, {
+      length: PR_BODY_TRUNCATE_SIZE,
+      omission: omissionText,
+    })
+  }
```
Comment (simoneb) [inline src/utils/releaseNotes.js:74]: this logic contains a big bug

**Review by simoneb — CHANGES_REQUESTED** [review]
see inline comment

File: src/utils/releaseNotes.js (hunk 1 above)
Comment (sameer-coder) [reply src/utils/releaseNotes.js:74]: I have moved the metadata to the top of the template so it doesn't get truncated

Comment (simoneb) [reply src/utils/releaseNotes.js:74]: can we please truncate the release notes so that the truncation logic doesn't depend on where the release metadata is positioned in the body of the PR?

**Review by simoneb — COMMENTED** [review]
I still don't like this solution too much. Let's keep the release meta in the template, but truncate the release notes instead.

Sorry for nitpicking, I think we should come up with a functional and clean solution.

**Comment by sameer-coder** [comment]
> I still don't like this solution too much. Let's keep the release meta in the template, but truncate the release notes instead.
> 
> Sorry for nitpicking, I think we should come up with a functional and clean solution.

Ok. If the length of the release notes is more than 60K then I will truncate it to 60K. The rest of the template should take about 1.5K characters so the final PR body length will be always within limit.

Alternatively, if we first check that the rendered PR body exceeds 65536 and on basis of that decide if we need to truncate the release notes then that would mean running the template twice which is not ideal so I will not use this approach.

**Comment by sameer-coder** [comment]
> I still don't like this solution too much. Let's keep the release meta in the template, but truncate the release notes instead.
> 
> Sorry for nitpicking, I think we should come up with a functional and clean solution.

I have changed the code so that if the length of the release notes is more than 60K then it will truncate it to 60K. The rest of the template should take about 1.5K characters max so the final PR body length will be always within limit.

Alternatively, if we first check that the rendered PR body exceeds 65536 and on basis of that decide if we need to truncate the release notes then that would mean running the template twice which is not ideal so I will not use this approach.

File: src/openPr.js [hunk 2]
```diff
@@ -134,6 +105,10 @@ module.exports = async function ({ context, inputs, packageVersion }) {
       },
       inputs
     )
+    if (response?.status !== 201) {
+      const errMessage = response?.message || 'PR creation failed'
```
Comment (simoneb) [inline src/openPr.js:109]: are we sure that this is where the message will appear in case of an error?

File: src/utils/releaseNotes.js [hunk 3]
```diff
@@ -30,4 +35,45 @@ function getPrNumbersFromReleaseNotes(releaseNotes) {
   return [...new Set(allPrNumbers)]
 }
 
+exports.getPRBody = (
```
Comment (simoneb) [inline src/utils/releaseNotes.js:38]: for consistency, let's declare a plain function and then export it at the bottom of this module, as we're doing with the other function

File: src/utils/releaseNotes.js [hunk 4]
```diff
@@ -30,4 +35,45 @@ function getPrNumbersFromReleaseNotes(releaseNotes) {
...
+    id: draftRelease.id,
+    version: newVersion,
+    npmTag: inputs['npm-tag'],
+    opticUrl: inputs['optic-url'],
+  }
+
+  const draftReleaseBody = draftRelease?.body || ''
+  if (draftReleaseBody.length > PR_BODY_TRUNCATE_SIZE) {
+    const omissionText =
+      '. *Note: Part of the release notes have been omitted from this message, as the content exceeds the size limit*'
```
Comment (simoneb) [inline src/utils/releaseNotes.js:59]:
```suggestion
      '> Some of these release notes have been truncated to respect Pull Request body size limits'
```

**Review by simoneb — COMMENTED** [review]
a few more comments

File: src/openPr.js (hunk 2 above)
Comment (sameer-coder) [reply src/openPr.js:109]: yes, I tested this by simulating an error

File: src/utils/releaseNotes.js [hunk 5]
```diff
@@ -30,4 +35,46 @@ function getPrNumbersFromReleaseNotes(releaseNotes) {
...
+    artifact,
+    syncTags: /true/i.test(inputs['sync-semver-tags']),
+    author,
+  })
+
+  return prBody
+}
+
 exports.getPrNumbersFromReleaseNotes = getPrNumbersFromReleaseNotes
+exports.getPRBody = getPRBody
```
Comment (simoneb) [inline src/utils/releaseNotes.js:80]: nit: let's slightly simplify this to module.exports = { ... }

File: test/releaseNotes.test.js [hunk 6]
```diff
@@ -36,3 +42,54 @@ tap.test('Should return the correct PR numbers', async () => {
...
+
+  const truncatedPrBody = getPRBody(_template(tpl), {
+    newVersion: '1.0.0',
+    draftRelease: { id: 1, body: longPrBody },
+    inputs: [],
+    author: 'test',
+    artifact: null,
+  })
+  tap.ok(truncatedPrBody.length < 65536)
+  tap.ok(
```
Comment (simoneb) [inline test/releaseNotes.test.js:90]: this is not the right way to assert here (it was probably a mistake in existing tests too). you should use the first argument provided to the test function instead

**Review by simoneb — APPROVED** [review]
